### ISSUE TITLE
Split up functions into multiple modules

### ISSUE THREAD

**Issue by npmccallum** [latchset/pyjose#5]
Instead of this:

```
import jose
jose.jwk_generate({"alg": "A128GCM"})
```

We want this:

```
import jose.jwk
jose.jwk.generate({"alg": "A128GCM"})
```

**Comment by npmccallum** [comment]
This might get tricky around the compact conversion functions. I definitely want:

```
import jose
jose.to_compact(...)
jose.from_compact(...)
```

**Comment by tiran** [comment]
There are multiple ways to accomplish your goal. The simplest way is to rename the C extension _jose and then introduce a jose package and modules:

```
jose/__init__.py
jose/_jose.so
jose/jwk.py
```

Each module imports the function it is interested in:

```
# jwk.py
from ._jose import jwk_generate as generate
```

or wraps the functions:

```
# jwk.py
from . import _jose

def generate(jwk):
    return _jose.jwk_generate(jwk)
```

**Comment by npmccallum** [comment]
Regarding module layout, I'm thinking:

```
jose.jwk.generate()
jose.jwk.clean()
jose.jwk.allowed()
jose.jwk.thumbprint()
jose.jwk.exchange()

jose.jws.sign()
jose.jws.verify()
jose.jws.merge_header()

jose.jwe.wrap()
jose.jwe.encrypt()
jose.jwe.unwrap()
jose.jwe.decrypt()
jose.jwe.merge_header()

jose.compact.dumps()
jose.compact.loads()
```

The main change here is that `jose_to_compact()` and `jose_from_compact()` become just serialization functions for a JWS/JWE object. This mimics the json module. The base jose module would be empty.

I think this layout should be easy to make. Something like:

```
jose/__init__.py
jose/jwk.so
jose/jws.so
jose/jwe.so
jose/compact.so
```

Thoughts?

**Comment by tiran** [comment]
I advice against multiple shared libraries. It's a common practice to have an internal C module and do the rest in Python --  one internal shared library and a couple of Python modules as facade.

It's  easier, faster and simpler for development, too.In Python 2 a C extension does not have the ability to support sub-namespaces in packages. You can't easily share data between C extensions, e.g. exception types. Cython makes it a bit easier but it is still hacky.

## Layout

```
jose/__init__.py
jose/_jose.so
jose/jwk.py
jose/jws.py
jose/jwe.py
jose/compact.py
```
