### ISSUE TITLE
Review all string inputs/output for proper bytes/unicode types

### ISSUE THREAD

**Issue by npmccallum** [latchset/pyjose#7]
Some of our functions take bytes and/or unicode inputs. We probably should review these on a case-by-case basis and ensure proper typing and input flexibility.

**Comment by tiran** [comment]
PR #10 adds two helper functions to convert between Python text datatypes (str, ascii unicode in Python 2; ascii str in Python 3) and char*. I can apply them to the rest of the file if you like the approach.
